### ISSUE TITLE
panic due to concurrent map read / write

### ISSUE THREAD

**Issue by tiziano88** [x-cray/logrus-prefixed-formatter#26]
This happened a few times in a server under intense load (with lots of goroutines).

```
fatal error: concurrent map read and map write
time="2018-01-17T22:40:01.546780408Z" level=info msg="sending slack message" prefix="tools/prober" source="main.sendSlackMessage([...]/tools/prober/slack.go:124)"

goroutine 276445 [running]:
runtime.throw(0xb28baa, 0x21)
        /usr/lib/google-golang/src/runtime/panic.go:608 +0x9e fp=0xc4340ab5b8 sp=0xc4340ab598 pc=0x542cce
runtime.mapaccess1_faststr(0xa5e5c0, 0xc4201d1350, 0xb1659c, 0x6, 0xa1d0e0)
        /usr/lib/google-golang/src/runtime/hashmap_fast.go:217 +0x43a fp=0xc4340ab610 sp=0xc4340ab5b8 pc=0x522f7a
[...]/vendor/github.com/x-cray/logrus-prefixed-formatter.(*TextFormatter).Format(0xc420080aa0, 0xc42c929cc0, 0xc42014a400, 0xafeb60, 0xc421e280e0, 0x0, 0xc42def1740)
        /[...]/vendor/github.com/x-cray/logrus-prefixed-formatter/formatter.go:216 +0x4a3 fp=0xc4340ab7a0 sp=0xc4340ab610 pc=0x939a83
[...]/vendor/github.com/sirupsen/logrus.Entry.log(0xc420080460, 0xc4201d1350, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc400000004, ...)
        /[...]/vendor/github.com/sirupsen/logrus/entry.go:109 +0x22c fp=0xc4340ab870 sp=0xc4340ab7a0 pc=0x902c4c
[...]/vendor/github.com/sirupsen/logrus.(*Entry).Info(0xc4201d2730, 0xc4340ab948, 0x1, 0x1)
        /[...]/vendor/github.com/sirupsen/logrus/entry.go:144 +0xac fp=0xc4340ab8e0 sp=0xc4340ab870 pc=0x90322c
main.sendSlackMessage(0xc428cd56b0, 0xc, 0xb2192a)
        /[...]/tools/prober/slack.go:124 +0x7d fp=0xc4340ab968 sp=0xc4340ab8e0 pc=0x9afe8d
main.(*environment).slackAlerts(0xc420199490)
        /[...]/tools/prober/slack.go:70 +0x4e3 fp=0xc4340abaf0 sp=0xc4340ab968 pc=0x9af333
main.(*environment).check(0xc420199490)
        /[...]/tools/prober/prober.go:325 +0x13fb fp=0xc4340abfa0 sp=0xc4340abaf0 pc=0x9ae45b
main.(*environment).start.func1(0xc4201ee410, 0xc420199490)
        /[...]/tools/prober/prober.go:344 +0x5a fp=0xc4340abfd0 sp=0xc4340abfa0 pc=0x9b030a
runtime.goexit()
        /usr/lib/google-golang/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4340abfd8 sp=0xc4340abfd0 pc=0x5735d1
created by main.(*environment).start
        /[...]/tools/prober/prober.go:342 +0x9f
```

**Comment by tiziano88** [comment]
Actually this seems related to a hook that was mutating the underlying entry, e.g. see https://github.com/sirupsen/logrus/issues/364 .
